#! perl -w

# this extension was found at https://aur.archlinux.org/packages.php?ID=42497 - thanks!

sub on_user_command {
	my ($self, $cmd) = @_;
	if ($cmd eq "fullscreen:switch") {
		my $dummy = `wmctrl -r :ACTIVE: -b toggle,fullscreen,above` ;
	}
}
